select top 10 * from customer;


--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum( purchase_amount ) as revenue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer
where discount_applied = 'Yes'
and purchase_amount >= (select AVG(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
    item_purchased,
    AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC;



--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type , AVG(purchase_amount) as average_purchase_amount from customer 
Where shipping_type = 'standard' or shipping_type = 'express'
group by shipping_type;



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select 
subscription_status,
count(distinct  customer_id) as total_customer , 
sum(purchase_amount) as total_spent , 
avg(purchase_amount) as Average_spent 
from customer 
group by subscription_status ;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased ,   COUNT(*) AS total_purchases, 
 SUM(CASE 
            WHEN discount_applied = 'Yes' THEN 1 
            ELSE 0 
        END) AS discounted_purchases,
    (SUM(CASE 
            WHEN discount_applied = 'Yes' THEN 1 
            ELSE 0 
        END) * 100.0 / COUNT(*)) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
    with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 



WITH product_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
      item_rank, 
      item_purchased,
       category,
 purchase_count

FROM product_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(DISTINCT customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group , sum(purchase_amount) total_spent
from customer
group by age_group
ORDER BY total_spent desc;


--Q11. Do customers who receive discounts place more repeat purchases compared to customers who never receive discounts?

SELECT 
    discount_applied,
    AVG(previous_purchases) AS avg_repeat_purchases,
    COUNT(DISTINCT customer_id) AS customer_count
FROM customer
GROUP BY discount_applied;
